### ISSUE TITLE
Upgrade to Elm v0.19

### ISSUE THREAD

**Issue by Libbum** [ktonon/elm-crypto#5]
I'm happy to do the conversion if you don't have the time at the moment. Since there's a dependency on `elm-word` I've started there: ktonon/elm-word#4

**Comment by billstclair** [comment]
I did the conversion: https://github.com/ktonon/elm-crypto/pull/6

**Comment by cscalfani** [comment]
+1

**Comment by aaahrens** [comment]
+1

**Comment by billstclair** [comment]
I'd much prefer to keep it yours, unless you really want to give up maintenance. Then I'm willing to take it over.

**Comment by ktonon** [comment]
Alright, I’ll aim to have this published by the end of the week then.

**Comment by ktonon** [comment]
Published as elm 0.19.0 package. See #6
